language: node_js
node_js: stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_a7e52f101156_key -iv $encrypted_a7e52f101156_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config user.name "Fanite"
- git config user.email "bellong@vip.qq.com"
- git submodule update --init --sync --recursive

install:
- npm install -g hexo-cli
- npm install
addons:
  ssh_known_hosts: git.coding.net
script:
- hexo clean
- hexo g
- hexo d
